#!/usr/bin/env python3
"""Regenerate the shared cross-runtime fixtures under ``testdata/``.

SPEC.md §37.1 requires one integration owner to freeze schemas, config, canonical types,
angle/quaternion vectors, WMM vectors, replay fixtures and rule boundaries **before** platform
work diverges, and forbids either platform agent editing them unilaterally. This script is the
provenance for the generated part of that set: it is committed alongside its output so a
reviewer can see how every expected value was derived, and rerunning it must reproduce the
committed files byte for byte.

Every expectation here is computed from the **specification formula written inline**, never by
calling ``fscompass_analysis``. A fixture generated by the implementation it is meant to police
proves only that the implementation agrees with itself; §37 rule 12 exists because that is the
tempting shortcut when a gate fails.

Usage::

    python3 scripts/generate-shared-fixtures.py            # rewrite testdata/
    python3 scripts/generate-shared-fixtures.py --check     # fail if the tree is stale
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

FIXTURE_VERSION = "fixtures-v1"

#: §36 Phase 1 exit: "identical fixtures agree within 1e-6 deg for angle math". The fixtures
#: are stored to full double precision and compared with a tighter working tolerance, so a
#: real divergence is visible long before it reaches the declared limit.
DECLARED_ANGLE_TOLERANCE_DEG = 1e-6
WORKING_ANGLE_TOLERANCE_DEG = 1e-9


# --------------------------------------------------------------------------------------
# SPEC.md §9 / §9.1 formulas, written out rather than imported.
# --------------------------------------------------------------------------------------
def normalize360(deg: float) -> float:
    wrapped = ((deg % 360.0) + 360.0) % 360.0
    return 0.0 if wrapped == 360.0 else wrapped + 0.0


def shortest_signed_difference_deg(a: float, b: float) -> float:
    radians = math.radians(a - b)
    delta = math.degrees(math.atan2(math.sin(radians), math.cos(radians)))
    return 180.0 if delta == -180.0 else delta


def quantile(values: list[float], q: float) -> float:
    ordered = sorted(values)
    n = len(ordered)
    return ordered[min(n - 1, max(0, math.ceil(q * n) - 1))]


def median(values: list[float]) -> float:
    ordered = sorted(values)
    n = len(ordered)
    if n % 2 == 1:
        return ordered[(n - 1) // 2]
    return (ordered[n // 2 - 1] + ordered[n // 2]) / 2.0


def circular_mean_and_resultant(samples: list[float]) -> tuple[float | None, float]:
    n = len(samples)
    if n == 0:
        return None, 0.0
    cosine = sum(math.cos(math.radians(value)) for value in samples) / n
    sine = sum(math.sin(math.radians(value)) for value in samples) / n
    resultant = min(1.0, max(0.0, math.hypot(cosine, sine)))
    if cosine == 0.0 and sine == 0.0:
        return None, resultant
    return normalize360(math.degrees(math.atan2(sine, cosine))), resultant


def sector_index(heading: float, first_center: float, width: float, count: int) -> int:
    return int(math.floor(normalize360(heading - first_center + width / 2.0) / width)) % count


def _offset_within_sector(heading: float, first_center: float, width: float) -> float:
    """How far past its own start boundary ``heading`` sits, in ``[0, width)``.

    Derived from the *same* wrapped quantity ``sector_index`` uses, so the index and the
    offset cannot disagree by a rounding bit at a boundary.
    """
    wrapped = normalize360(heading - first_center + width / 2.0)
    return wrapped - math.floor(wrapped / width) * width


def straddle_indices(
    heading: float, bound: float, first_center: float, width: float, count: int
) -> list[int]:
    """Every sector intersecting the closed circular interval ``[h - bound, h + bound]``.

    Counted from the arc length rather than by walking until the end index is met: at a bound
    approaching 180 deg the interval wraps almost the whole circle and its two endpoints land
    in the *same* sector, which a walk-until-equal would report as one sector instead of 24.
    """
    if 2.0 * bound >= 360.0:
        return []
    low = heading - bound
    start = sector_index(low, first_center, width, count)
    offset = _offset_within_sector(low, first_center, width)
    spanned = min(count, 1 + int(math.floor((offset + 2.0 * bound) / width)))
    return [(start + step) % count for step in range(spanned)]


# --------------------------------------------------------------------------------------
# Fixture builders
# --------------------------------------------------------------------------------------
def build_circular_math() -> dict:
    normalize_inputs = [
        -720.0,
        -540.0,
        -360.0,
        -0.0,
        0.0,
        1.0,
        -1.0,
        359.9999999,
        360.0,
        720.0,
        180.0,
        -179.5,
        1000000000.5,
    ]
    # §33.1/§35: both orderings of at least two distinct antipodal pairs. A test that only
    # checks deltaDeg(180, 0) passes on a broken implementation.
    signed_pairs = [
        (0.0, 180.0),
        (180.0, 0.0),
        (90.0, 270.0),
        (270.0, 90.0),
        (120.0, 300.0),
        (300.0, 120.0),
        (10.0, 350.0),
        (350.0, 10.0),
        (1.0, 359.0),
        (359.0, 1.0),
        (0.0, 0.0),
        (45.0, 44.0),
        (44.0, 45.0),
        (0.0, 90.0),
        (90.0, 0.0),
        (-10.0, 350.0),
        (720.0, 0.0),
    ]
    target_pairs = [
        (359.0, 1.0),
        (1.0, 359.0),
        (0.0, 180.0),
        (180.0, 0.0),
        (90.0, 275.0),
        (350.0, 10.0),
        (10.0, 350.0),
    ]
    return {
        "fixtureVersion": FIXTURE_VERSION,
        "specSections": ["§3", "§9", "§33.1"],
        "declaredAngleToleranceDeg": DECLARED_ANGLE_TOLERANCE_DEG,
        "workingAngleToleranceDeg": WORKING_ANGLE_TOLERANCE_DEG,
        "normalize360": [
            {"inputDeg": value, "expectedDeg": normalize360(value)} for value in normalize_inputs
        ],
        "shortestSignedDifferenceDeg": [
            {"aDeg": a, "bDeg": b, "expectedDeg": shortest_signed_difference_deg(a, b)}
            for a, b in signed_pairs
        ],
        "shortestTargetDeltaDeg": [
            {
                "currentDeg": current,
                "targetDeg": target,
                "expectedDeg": shortest_signed_difference_deg(target, current),
            }
            for current, target in target_pairs
        ],
        "absoluteCircularDifferenceDeg": [
            {"aDeg": a, "bDeg": b, "expectedDeg": abs(shortest_signed_difference_deg(a, b))}
            for a, b in signed_pairs
        ],
        "rejectedNonFiniteTokens": ["NAN", "POSITIVE_INFINITY", "NEGATIVE_INFINITY"],
    }


def build_estimators() -> dict:
    windows = [
        [1.0],
        [1.0, 2.0],
        [3.0, 1.0, 2.0],
        [1.0, 2.0, 3.0, 4.0],
        [float(index) for index in range(1, 21)],
        [float(index) for index in range(1, 101)],
        [5.0, 5.0, 5.0, 5.0, 5.0],
        [-3.0, -1.0, 0.0, 2.5, 7.25],
    ]
    probabilities = [0.0, 0.5, 0.9, 0.95, 0.99, 1.0]
    return {
        "fixtureVersion": FIXTURE_VERSION,
        "specSections": ["§9.1"],
        "estimator": "NEAREST_RANK",
        "definition": "quantile(x, q) = x[min(n-1, max(0, ceil(q*n) - 1))] over x sorted ascending",
        "quantile": [
            {
                "values": window,
                "probability": probability,
                "expected": quantile(window, probability),
            }
            for window in windows
            for probability in probabilities
        ],
        "median": [{"values": window, "expected": median(window)} for window in windows],
        "undefinedOnEmptyInput": True,
    }


def build_circular_aggregate(profile: dict) -> dict:
    minimum_resultant = float(profile["minCircularResultantLength"])
    windows = [
        {"id": "tight-cluster", "samples": [84.7, 85.3, 84.9, 85.4, 85.0]},
        {"id": "north-wrap", "samples": [359.0, 359.5, 0.0, 0.5, 1.0]},
        {"id": "single-sample", "samples": [123.456]},
        {"id": "antipodal-pair-undefined-mean", "samples": [0.0, 180.0]},
        {"id": "four-quadrants-undefined-mean", "samples": [0.0, 90.0, 180.0, 270.0]},
        {"id": "empty-window", "samples": []},
    ]
    entries = []
    for window in windows:
        mean, resultant = circular_mean_and_resultant(window["samples"])
        entry = {
            "id": window["id"],
            "samples": window["samples"],
            "expectedMeanDeg": mean,
            "expectedResultantLength": resultant,
            "meanIsDefined": mean is not None,
            # §15 decision 3. For an antipodal pair the sines cancel to ~6e-17 rather than
            # to zero, so the mean is numerically defined and arbitrary; only the configured
            # resultant gate rejects it.
            "expectedCircularMeanUndefinedUnderGate": (
                mean is None or resultant < minimum_resultant
            ),
        }
        if mean is not None:
            residuals = [
                abs(shortest_signed_difference_deg(sample, mean)) for sample in window["samples"]
            ]
            entry["expectedResidualsDeg"] = residuals
            entry["expectedResidualP95Deg"] = quantile(residuals, 0.95)
        entries.append(entry)
    return {
        "fixtureVersion": FIXTURE_VERSION,
        "specSections": ["§15", "§19"],
        "minCircularResultantLength": minimum_resultant,
        "weights": "UNIFORM",
        "trimming": "NONE",
        "windows": entries,
    }


def _quaternion_from_rotation_matrix(m: list[list[float]]) -> list[float]:
    """Shepperd's method, written inline so the fixture does not inherit an implementation."""
    trace = m[0][0] + m[1][1] + m[2][2]
    if trace > 0.0:
        s = math.sqrt(trace + 1.0) * 2.0
        q = [(m[2][1] - m[1][2]) / s, (m[0][2] - m[2][0]) / s, (m[1][0] - m[0][1]) / s, 0.25 * s]
    elif m[0][0] > m[1][1] and m[0][0] > m[2][2]:
        s = math.sqrt(1.0 + m[0][0] - m[1][1] - m[2][2]) * 2.0
        q = [0.25 * s, (m[0][1] + m[1][0]) / s, (m[0][2] + m[2][0]) / s, (m[2][1] - m[1][2]) / s]
    elif m[1][1] > m[2][2]:
        s = math.sqrt(1.0 + m[1][1] - m[0][0] - m[2][2]) * 2.0
        q = [(m[0][1] + m[1][0]) / s, 0.25 * s, (m[1][2] + m[2][1]) / s, (m[0][2] - m[2][0]) / s]
    else:
        s = math.sqrt(1.0 + m[2][2] - m[0][0] - m[1][1]) * 2.0
        q = [(m[0][2] + m[2][0]) / s, (m[1][2] + m[2][1]) / s, 0.25 * s, (m[1][0] - m[0][1]) / s]
    norm = math.sqrt(sum(component * component for component in q))
    return [component / norm for component in q]


def _matrix_from_columns(c1, c2, c3) -> list[list[float]]:
    """Columns are the ENU images of device +x, +y, +z respectively."""
    return [[c1[row], c2[row], c3[row]] for row in range(3)]


def build_attitude_golden() -> dict:
    up = (0.0, 0.0, 1.0)
    north = (0.0, 1.0, 0.0)
    east = (1.0, 0.0, 0.0)
    south = (0.0, -1.0, 0.0)
    west = (-1.0, 0.0, 0.0)

    def flat(top_edge_enu, right_enu):
        # face-up: device +z maps to Up.
        return _matrix_from_columns(right_enu, top_edge_enu, up)

    def wall(outward_normal_enu, right_enu):
        # phone upright against a wall: device +y (top edge) maps to Up.
        return _matrix_from_columns(right_enu, up, outward_normal_enu)

    cases = [
        {
            "id": "flat-top-edge-north",
            "measurementMode": "FLAT_TOP_EDGE",
            "matrix": flat(north, east),
            "expectedHeadingDeg": 0.0,
            "expectedElevationDeg": 0.0,
        },
        {
            "id": "flat-top-edge-east",
            "measurementMode": "FLAT_TOP_EDGE",
            "matrix": flat(east, south),
            "expectedHeadingDeg": 90.0,
            "expectedElevationDeg": 0.0,
        },
        {
            "id": "flat-top-edge-south",
            "measurementMode": "FLAT_TOP_EDGE",
            "matrix": flat(south, west),
            "expectedHeadingDeg": 180.0,
            "expectedElevationDeg": 0.0,
        },
        {
            "id": "flat-top-edge-west",
            "measurementMode": "FLAT_TOP_EDGE",
            "matrix": flat(west, north),
            "expectedHeadingDeg": 270.0,
            "expectedElevationDeg": 0.0,
        },
        {
            "id": "wall-outward-normal-north",
            "measurementMode": "WALL_FLUSH_BACK",
            "matrix": wall(north, west),
            "expectedHeadingDeg": 0.0,
            "expectedElevationDeg": 0.0,
        },
        {
            "id": "wall-outward-normal-east",
            "measurementMode": "WALL_FLUSH_BACK",
            "matrix": wall(east, north),
            "expectedHeadingDeg": 90.0,
            "expectedElevationDeg": 0.0,
        },
        {
            "id": "wall-outward-normal-south",
            "measurementMode": "WALL_FLUSH_BACK",
            "matrix": wall(south, east),
            "expectedHeadingDeg": 180.0,
            "expectedElevationDeg": 0.0,
        },
        {
            "id": "wall-outward-normal-west",
            "measurementMode": "WALL_FLUSH_BACK",
            "matrix": wall(west, south),
            "expectedHeadingDeg": 270.0,
            "expectedElevationDeg": 0.0,
        },
        {
            # The singular case §14 requires to be rejected rather than assigned a heading:
            # in a face-up pose the wall axis (device +z) points straight up.
            "id": "wall-axis-vertical-singular",
            "measurementMode": "WALL_FLUSH_BACK",
            "matrix": flat(north, east),
            "expectedHeadingDeg": None,
            "expectedElevationDeg": 90.0,
            "expectIllConditioned": True,
            "expectExactlySingular": True,
        },
        {
            # The mirror case, and the more instructive one: in a wall pose the top edge is
            # vertical but its horizontal projection comes out as 2.2e-16 rather than zero,
            # so atan2 returns a confident arbitrary 180 deg. Only the elevation gate rejects
            # it — which is exactly why §11.1 forbids comparing it to the wall normal.
            "id": "flat-axis-vertical-ill-conditioned",
            "measurementMode": "FLAT_TOP_EDGE",
            "matrix": wall(north, west),
            "expectedHeadingDeg": None,
            "expectedElevationDeg": 90.0,
            "expectIllConditioned": True,
            "expectExactlySingular": False,
        },
    ]
    for case in cases:
        case["quaternionDeviceToReferenceEnuXyzw"] = _quaternion_from_rotation_matrix(
            case["matrix"]
        )

    # R49: the Core Motion native frame (+X true north, +Z vertical, hence +Y west) converted
    # to canonical REFERENCE_ENU under the *declared* convention. Phase 2 must confirm the
    # convention itself against the pinned SDK.
    core_motion_native = _matrix_from_columns(
        (0.0, -1.0, 0.0),  # device +x → east → native (0, -1, 0)
        (1.0, 0.0, 0.0),  # device +y → north → native (1, 0, 0)
        (0.0, 0.0, 1.0),  # device +z → up → native (0, 0, 1)
    )
    return {
        "fixtureVersion": FIXTURE_VERSION,
        "specSections": ["§3", "§11.1", "§14"],
        "quaternionComponentOrder": "XYZW",
        "transformDirection": "DEVICE_TO_REFERENCE",
        "canonicalFrame": "REFERENCE_ENU",
        "deviceAxes": {
            "x": "RIGHT",
            "y": "PORTRAIT_TOP_EDGE",
            "z": "OUTWARD_SCREEN_NORMAL",
        },
        "modeReferenceVectors": {
            "FLAT_TOP_EDGE": [0.0, 1.0, 0.0],
            "WALL_FLUSH_BACK": [0.0, 0.0, 1.0],
        },
        "modeAxisElevationGateKey": {
            "FLAT_TOP_EDGE": "flatModePitchAbsMaxDeg",
            "WALL_FLUSH_BACK": "wallNormalElevationAbsMaxDeg",
        },
        "cases": cases,
        "nativeFrameConversion": [
            {
                "id": "core-motion-flat-north",
                "nativeFrame": "CORE_MOTION_X_TRUE_NORTH_Z_VERTICAL",
                "verification": "DECLARED_UNVERIFIED",
                "nativeQuaternionXyzw": _quaternion_from_rotation_matrix(core_motion_native),
                "expectedCanonicalQuaternionXyzw": _quaternion_from_rotation_matrix(
                    flat(north, east)
                ),
                "expectedFlatHeadingDeg": 0.0,
            }
        ],
    }


def build_fengshui_classification(rule_set: dict) -> dict:
    count = int(rule_set["sectorCount"])
    width = float(rule_set["sectorWidthDeg"])
    first_center = float(rule_set["firstSectorCenterDeg"])
    names = {int(sector["index"]): sector["name"] for sector in rule_set["sectors"]}
    epsilon = 1e-9

    cases = []
    for index in range(count):
        center = normalize360(first_center + index * width)
        start = normalize360(center - width / 2.0)
        end = normalize360(center + width / 2.0)
        probes = [
            ("center", center),
            ("start-boundary", start),
            ("end-boundary", end),
            ("start-minus-epsilon", start - epsilon),
            ("start-plus-epsilon", start + epsilon),
            ("start-minus-0.1", start - 0.1),
            ("start-plus-0.1", start + 0.1),
            ("start-minus-1.0", start - 1.0),
            ("start-plus-1.0", start + 1.0),
        ]
        for label, raw in probes:
            heading = normalize360(raw)
            expected = sector_index(heading, first_center, width, count)
            cases.append(
                {
                    "id": f"sector-{index:02d}-{label}",
                    "declaredSectorIndex": index,
                    "headingDeg": heading,
                    "expectedSectorIndex": expected,
                    "expectedSectorName": names[expected],
                }
            )

    straddle_cases = []
    for heading, bound, note in [
        (189.0, 7.0, "the §22.1 example: 7.0 deg straddles the 187.5 boundary"),
        (0.0, 0.0, "a zero bound is one sector"),
        (0.0, 1.0, "north wrap, symmetric across 0/360"),
        (352.5, 0.0, "exactly on the boundary separating ren and zi"),
        (352.5, 0.5, "straddling that boundary"),
        (7.5, 0.0, "exactly on a boundary belongs to the sector it starts"),
        (100.0, 7.5, "a bound above 7.5 guarantees at least two sectors"),
        (100.0, 20.0, "above 15 deg guarantees at least three"),
        (
            10.0,
            179.0,
            "nearly the whole circle: both endpoints land in the same sector, which a "
            "walk-until-equal implementation would report as one sector instead of 24",
        ),
        (10.0, 180.0, "2*bound == 360: no classification is possible"),
        (10.0, 200.0, "2*bound > 360: no classification is possible"),
    ]:
        indices = straddle_indices(heading, bound, first_center, width, count)
        straddle_cases.append(
            {
                "headingDeg": heading,
                "reportedBound95Deg": bound,
                "note": note,
                "expectedSectorIndices": indices,
                "expectedSectorNames": [names[index] for index in indices],
                "expectedBoundaryStraddled": len(indices) != 1,
                "classificationPossible": len(indices) > 0,
            }
        )

    return {
        "fixtureVersion": FIXTURE_VERSION,
        "specSections": ["§21.1", "§21.3", "§21.4"],
        "ruleSetVersion": rule_set["ruleSetVersion"],
        "sectorIndexFormula": (
            "floor(normalize360(h - firstSectorCenterDeg + sectorWidthDeg/2) / sectorWidthDeg) "
            "mod sectorCount"
        ),
        "boundaryEpsilonDeg": epsilon,
        "sectorCases": cases,
        "straddleCases": straddle_cases,
    }


def build_fengshui_reference_transform() -> dict:
    """§21.2 under **both** hidden Google hypotheses and both ruleset references.

    Let ``g`` be the Google output and ``d`` the declination. If Google secretly emitted true
    north, TRUE uses ``g`` exactly and MAGNETIC uses ``g-d`` exactly. If Google secretly
    emitted magnetic north, the TRUE point ``g`` is wrong by ``|d|`` and the derived MAGNETIC
    point ``g-d`` is *also* wrong by ``|d|``; ``referenceAmbiguityBound95Deg = |d|`` covers
    either hypothesis. Subtracting ``d`` for a magnetic ruleset MUST NOT zero the term.
    """
    cases = []
    for declination in (1.5, -1.5):
        for google_output in (0.0, 7.4, 352.6, 189.0):
            for hidden in ("GOOGLE_EMITTED_TRUE", "GOOGLE_EMITTED_MAGNETIC"):
                actual_true = (
                    google_output
                    if hidden == "GOOGLE_EMITTED_TRUE"
                    else normalize360(google_output + declination)
                )
                for reference_selection in ("TRUE", "MAGNETIC"):
                    point_estimate = (
                        google_output
                        if reference_selection == "TRUE"
                        else normalize360(google_output - declination)
                    )
                    truth = (
                        actual_true
                        if reference_selection == "TRUE"
                        else normalize360(actual_true - declination)
                    )
                    cases.append(
                        {
                            "id": (
                                f"d{declination:+}-g{google_output}-{hidden}-{reference_selection}"
                            ),
                            "caseKind": "HIDDEN_HYPOTHESIS",
                            "googleOutputDeg": google_output,
                            "declinationDeg": declination,
                            "hiddenHypothesis": hidden,
                            "referenceSelection": reference_selection,
                            "needleOffsetDeg": 0.0,
                            "expectedClassificationHeadingDeg": point_estimate,
                            "truthUnderHypothesisDeg": truth,
                            "referenceAmbiguityBound95Deg": abs(declination),
                            "expectedErrorDeg": abs(
                                shortest_signed_difference_deg(point_estimate, truth)
                            ),
                        }
                    )
    # A ruleset needle offset is a declared doctrinal plate convention, never an instrument
    # correction: it shifts the classification heading and nothing else. Its "error" against
    # an un-offset truth is the doctrine, not measurement uncertainty, so these cases are
    # tagged NEEDLE_OFFSET and are deliberately outside the ambiguity-coverage check.
    for offset in (7.5, -7.5):
        cases.append(
            {
                "id": f"needle-offset{offset:+}",
                "caseKind": "NEEDLE_OFFSET",
                "googleOutputDeg": 100.0,
                "declinationDeg": 0.0,
                "hiddenHypothesis": "GOOGLE_EMITTED_TRUE",
                "referenceSelection": "TRUE",
                "needleOffsetDeg": offset,
                "expectedClassificationHeadingDeg": normalize360(100.0 + offset),
                "truthUnderHypothesisDeg": 100.0,
                "referenceAmbiguityBound95Deg": 0.0,
                "expectedErrorDeg": abs(offset),
            }
        )
    return {
        "fixtureVersion": FIXTURE_VERSION,
        "specSections": ["§11", "§21.2"],
        "cases": cases,
    }


def build_uncertainty_composition(profile: dict) -> dict:
    """§19 composition cases, including the reachability-consistent §22.1 example (R62)."""
    return {
        "fixtureVersion": FIXTURE_VERSION,
        "specSections": ["§19", "§8.1.1", "§22.1"],
        "configVersion": profile["configVersion"],
        "cases": [
            {
                "id": "example-uncertified-flat-freehand-degrades",
                "note": (
                    "R62: the shipped §22.1 example. Fresh confident provider, clean field, "
                    "verified reference, level device — and still not a Precision Lock, "
                    "because the unknown-device floor plus freehand placement is 7.0 deg."
                ),
                "providerReportedBoundTermDeg": 1.8,
                "sampleBound95Deg": 0.62,
                "deviceFloor95Deg": profile["unknownDeviceFloor95Deg"],
                "placementBound95Deg": profile["flatFreehandPlacementBound95Deg"],
                "expectedBaseHeadingBound95Deg": 4.0,
                "expectedInstrumentBound95Deg": 4.0,
                "expectedReportedBound95Deg": 7.0,
                "expectedGradeLimitedBy": "DEVICE_FLOOR",
                "expectedMeasurementState": "DEGRADED",
            },
            {
                "id": "provider-term-absent-is-not-zero",
                "note": (
                    "R61: a wall path exposes no documented provider degree error. The term "
                    "is absent, and the max is taken over present values only — it does not "
                    "become a 0.0 that could lower the base."
                ),
                "providerReportedBoundTermDeg": None,
                "sampleBound95Deg": 0.4,
                "deviceFloor95Deg": profile["unknownDeviceFloor95Deg"],
                "placementBound95Deg": profile["wallFreehandPlacementBound95Deg"],
                "expectedBaseHeadingBound95Deg": 4.0,
                "expectedInstrumentBound95Deg": 4.0,
                "expectedReportedBound95Deg": 9.0,
                "expectedGradeLimitedBy": "PLACEMENT_UNCERTAINTY",
                "expectedMeasurementState": "DEGRADED",
            },
            {
                "id": "rv-term-cannot-lower-the-floor",
                "note": (
                    "R63: the AOSP-documented 95% rotation-vector term enters the base max "
                    "unconverted. Because the base is a max, adding it can only leave the "
                    "base unchanged or increase it."
                ),
                "providerReportedBoundTermDeg": 2.5,
                "sampleBound95Deg": 0.5,
                "deviceFloor95Deg": profile["unknownDeviceFloor95Deg"],
                "placementBound95Deg": profile["flatFreehandPlacementBound95Deg"],
                "expectedBaseHeadingBound95Deg": 4.0,
                "expectedInstrumentBound95Deg": 4.0,
                "expectedReportedBound95Deg": 7.0,
                "expectedGradeLimitedBy": "DEVICE_FLOOR",
                "expectedMeasurementState": "DEGRADED",
            },
            {
                "id": "rv-term-above-the-floor-widens-the-base",
                "note": "The same term when the provider reports worse uncertainty than the floor.",
                "providerReportedBoundTermDeg": 6.0,
                "sampleBound95Deg": 0.5,
                "deviceFloor95Deg": profile["unknownDeviceFloor95Deg"],
                "placementBound95Deg": profile["flatFreehandPlacementBound95Deg"],
                "expectedBaseHeadingBound95Deg": 6.0,
                "expectedInstrumentBound95Deg": 6.0,
                "expectedReportedBound95Deg": 9.0,
                "expectedGradeLimitedBy": "PROVIDER_ERROR",
                "expectedMeasurementState": "DEGRADED",
            },
            {
                "id": "certified-jig-locks",
                "note": (
                    "A certified floor plus a measured jig placement bound is the only shape "
                    "that reaches a lock under the shipped constants (§8.1.1 bootstrap)."
                ),
                "providerReportedBoundTermDeg": 1.0,
                "sampleBound95Deg": 0.5,
                "deviceFloor95Deg": 1.2,
                "placementBound95Deg": 0.5,
                "expectedBaseHeadingBound95Deg": 1.2,
                "expectedInstrumentBound95Deg": 1.2,
                "expectedReportedBound95Deg": 1.7,
                "expectedGradeLimitedBy": "DEVICE_FLOOR",
                "expectedMeasurementState": "PRECISION_LOCKED",
            },
            {
                "id": "suspect-field-blocks-a-freehand-lock",
                "note": (
                    "§8.1.1 row 3: SUSPECT adds 3.0 deg, which alone exceeds the 2.0 deg "
                    "flat-freehand instrument budget. The interference and placement terms "
                    "are both exactly 3.0 here, so gradeLimitedBy resolves by stable enum "
                    "order (§19) — PLACEMENT_UNCERTAINTY precedes INTERFERENCE_PENALTY. The "
                    "tie is the point: two runtimes must name the same one."
                ),
                "providerReportedBoundTermDeg": 1.0,
                "sampleBound95Deg": 0.5,
                "deviceFloor95Deg": 1.2,
                "placementBound95Deg": profile["flatFreehandPlacementBound95Deg"],
                "interferenceBound95Deg": profile["suspectInterferenceBound95Deg"],
                "expectedBaseHeadingBound95Deg": 1.2,
                "expectedInstrumentBound95Deg": 4.2,
                "expectedReportedBound95Deg": 7.2,
                "expectedGradeLimitedBy": "PLACEMENT_UNCERTAINTY",
                "expectedMeasurementState": "DEGRADED",
            },
            {
                "id": "ambiguity-and-declination-terms-add",
                "note": (
                    "§19: the non-base terms are different, additive error sources. The "
                    "declination term arrives through boundFromSigma exactly once (§19.2)."
                ),
                "providerReportedBoundTermDeg": 1.0,
                "sampleBound95Deg": 0.5,
                "deviceFloor95Deg": 1.2,
                "declinationModelBound95Deg": 0.4,
                "locationTimeSensitivityBound95Deg": 0.05,
                "referenceAmbiguityBound95Deg": 1.5,
                "placementBound95Deg": 0.5,
                "expectedBaseHeadingBound95Deg": 1.2,
                "expectedInstrumentBound95Deg": 3.15,
                "expectedReportedBound95Deg": 3.65,
                "expectedGradeLimitedBy": "REFERENCE_AMBIGUITY",
                "expectedMeasurementState": "PRECISION_LOCKED",
            },
        ],
    }


def build_magnetic_classification(profile: dict) -> dict:
    return {
        "fixtureVersion": FIXTURE_VERSION,
        "specSections": ["§16", "§11"],
        "configVersion": profile["configVersion"],
        "inclinationCases": [
            {
                "id": "northern-hemisphere-field-points-down",
                "upMicroTesla": -43.9,
                "magnitudeMicroTesla": 48.7,
                "expectedMeasuredInclinationPositiveDownDeg": math.degrees(
                    math.asin(max(-1.0, min(1.0, 43.9 / 48.7)))
                ),
            },
            {
                "id": "southern-hemisphere-field-points-up",
                "upMicroTesla": 43.9,
                "magnitudeMicroTesla": 48.7,
                "expectedMeasuredInclinationPositiveDownDeg": -math.degrees(
                    math.asin(max(-1.0, min(1.0, 43.9 / 48.7)))
                ),
            },
            {
                "id": "magnetic-equator-zero-inclination",
                "upMicroTesla": 0.0,
                "magnitudeMicroTesla": 32.0,
                "expectedMeasuredInclinationPositiveDownDeg": 0.0,
            },
            {
                "id": "clamped-beyond-unit-ratio",
                "upMicroTesla": -48.700000000000003,
                "magnitudeMicroTesla": 48.7,
                "expectedMeasuredInclinationPositiveDownDeg": 90.0,
            },
        ],
        "classifierCases": [
            {
                "id": "clean-all-features-present",
                "relativeMagnitudeResidual": 0.0167,
                "inclinationResidualDeg": 0.9,
                "stationaryFieldMadMicroTesla": 0.31,
                "pipelineAgreementDeg": 0.54,
                "expectedMagneticState": "CLEAN",
                "expectedPrecheckState": "CLEAN_FOR_REFERENCE",
            },
            {
                "id": "moving-device-stationary-mad-absent",
                "relativeMagnitudeResidual": 0.0167,
                "inclinationResidualDeg": 0.9,
                "stationaryFieldMadMicroTesla": None,
                "pipelineAgreementDeg": 0.54,
                "expectedMagneticState": "UNKNOWN",
                "expectedPrecheckState": "UNKNOWN",
            },
            {
                "id": "single-pipeline-agreement-absent",
                "relativeMagnitudeResidual": 0.0167,
                "inclinationResidualDeg": 0.9,
                "stationaryFieldMadMicroTesla": 0.31,
                "pipelineAgreementDeg": None,
                "expectedMagneticState": "UNKNOWN",
                "expectedPrecheckState": "CLEAN_FOR_REFERENCE",
            },
            {
                "id": "rotated-field-normal-magnitude",
                "note": (
                    "Failure mode 23: a disturbance that rotates the field vector with almost "
                    "no magnitude change. Magnitude alone would call this clean."
                ),
                "relativeMagnitudeResidual": 0.01,
                "inclinationResidualDeg": 14.0,
                "stationaryFieldMadMicroTesla": 0.4,
                "pipelineAgreementDeg": 1.0,
                "expectedMagneticState": "DISTURBED",
                "expectedPrecheckState": "NOT_CLEAN_FOR_REFERENCE",
            },
            {
                "id": "suspect-magnitude-only",
                "relativeMagnitudeResidual": profile[
                    "magneticMagnitudeResidualSuspectFraction"
                ],
                "inclinationResidualDeg": 0.5,
                "stationaryFieldMadMicroTesla": 0.4,
                "pipelineAgreementDeg": 1.0,
                "expectedMagneticState": "SUSPECT",
                "expectedPrecheckState": "NOT_CLEAN_FOR_REFERENCE",
            },
            {
                "id": "pipeline-disagreement-disturbed",
                "relativeMagnitudeResidual": 0.01,
                "inclinationResidualDeg": 0.5,
                "stationaryFieldMadMicroTesla": 0.4,
                "pipelineAgreementDeg": profile["pipelineDisagreementDisturbedDeg"],
                "expectedMagneticState": "DISTURBED",
                "expectedPrecheckState": "CLEAN_FOR_REFERENCE",
                "note": (
                    "R59: pipeline disagreement disturbs the final state but the precheck "
                    "never reads it, so the dependency order stays acyclic."
                ),
            },
            {
                "id": "negative-inclination-residual-uses-absolute-value",
                "relativeMagnitudeResidual": 0.01,
                "inclinationResidualDeg": -13.0,
                "stationaryFieldMadMicroTesla": 0.4,
                "pipelineAgreementDeg": 1.0,
                "expectedMagneticState": "DISTURBED",
                "expectedPrecheckState": "NOT_CLEAN_FOR_REFERENCE",
            },
            {
                "id": "saturated-sensor-is-invalid",
                "relativeMagnitudeResidual": 0.01,
                "inclinationResidualDeg": 0.5,
                "stationaryFieldMadMicroTesla": 0.4,
                "pipelineAgreementDeg": 1.0,
                "sensorSaturated": True,
                "expectedMagneticState": "INVALID",
                "expectedPrecheckState": "NOT_CLEAN_FOR_REFERENCE",
            },
        ],
    }


def build_reference_resolution(profile: dict) -> dict:
    return {
        "fixtureVersion": FIXTURE_VERSION,
        "specSections": ["§11", "§30.5"],
        "configVersion": profile["configVersion"],
        "cases": [
            {
                "id": "true-verified",
                "measurementMode": "FLAT_TOP_EDGE",
                "gAxisDeg": 189.0,
                "mAxisDeg": 180.71,
                "declinationDeg": 8.29,
                "precheckState": "CLEAN_FOR_REFERENCE",
                "expectedResolvedReference": "TRUE_VERIFIED",
                "expectedCorrectionDeg": 0.0,
                "expectedReferenceAmbiguityBound95Deg": 0.0,
                "expectedCanonicalTrueHeadingDeg": 189.0,
            },
            {
                "id": "true-corrected-from-magnetic",
                "measurementMode": "FLAT_TOP_EDGE",
                "gAxisDeg": 180.71,
                "mAxisDeg": 180.71,
                "declinationDeg": 8.29,
                "precheckState": "CLEAN_FOR_REFERENCE",
                "expectedResolvedReference": "TRUE_CORRECTED_FROM_MAGNETIC",
                "expectedCorrectionDeg": 8.29,
                "expectedReferenceAmbiguityBound95Deg": 0.0,
                "expectedCanonicalTrueHeadingDeg": 189.0,
                "note": (
                    "Failure mode 21: declination appears exactly once. A second application "
                    "here would give 197.29, a plausible bearing 2*d from the truth."
                ),
            },
            {
                "id": "small-declination-ambiguity",
                "measurementMode": "WALL_FLUSH_BACK",
                "gAxisDeg": 100.0,
                "mAxisDeg": 100.0,
                "declinationDeg": 1.5,
                "precheckState": "CLEAN_FOR_REFERENCE",
                "expectedResolvedReference": "TRUE_WITH_AMBIGUITY_BOUND",
                "expectedCorrectionDeg": 0.0,
                "expectedReferenceAmbiguityBound95Deg": 1.5,
                "expectedCanonicalTrueHeadingDeg": 100.0,
            },
            {
                "id": "true-verified-at-large-declination",
                "measurementMode": "FLAT_TOP_EDGE",
                "gAxisDeg": 100.0,
                "mAxisDeg": 92.0,
                "declinationDeg": 8.0,
                "precheckState": "CLEAN_FOR_REFERENCE",
                "expectedResolvedReference": "TRUE_VERIFIED",
                "expectedCorrectionDeg": 0.0,
                "expectedReferenceAmbiguityBound95Deg": 0.0,
                "expectedCanonicalTrueHeadingDeg": 100.0,
                "note": (
                    "The separation the hypothesis test relies on: |d| = 8 deg is well above "
                    "referenceSeparationMarginDeg, so the two hypotheses are distinguishable."
                ),
            },
            {
                "id": "unverified-both-hypotheses-far",
                "measurementMode": "FLAT_TOP_EDGE",
                "gAxisDeg": 100.0,
                "mAxisDeg": 140.0,
                "declinationDeg": 8.0,
                "precheckState": "CLEAN_FOR_REFERENCE",
                "expectedResolvedReference": "UNVERIFIED",
                "expectedCorrectionDeg": 0.0,
                "expectedReferenceAmbiguityBound95Deg": 0.0,
                "expectedCanonicalTrueHeadingDeg": None,
            },
            {
                "id": "precheck-not-clean-refuses-to-resolve",
                "measurementMode": "FLAT_TOP_EDGE",
                "gAxisDeg": 189.0,
                "mAxisDeg": 180.71,
                "declinationDeg": 8.29,
                "precheckState": "NOT_CLEAN_FOR_REFERENCE",
                "expectedResolvedReference": "UNVERIFIED",
                "expectedCorrectionDeg": 0.0,
                "expectedReferenceAmbiguityBound95Deg": 0.0,
                "expectedCanonicalTrueHeadingDeg": None,
                "expectedResidualsAbsent": True,
                "note": (
                    "R59: the engine does not manufacture a Google pipeline reference in "
                    "order to compute the evidence that would have resolved it."
                ),
            },
            {
                "id": "north-wrap-true-corrected",
                "measurementMode": "FLAT_TOP_EDGE",
                "gAxisDeg": 355.0,
                "mAxisDeg": 355.0,
                "declinationDeg": 8.29,
                "precheckState": "CLEAN_FOR_REFERENCE",
                "expectedResolvedReference": "TRUE_CORRECTED_FROM_MAGNETIC",
                "expectedCorrectionDeg": 8.29,
                "expectedReferenceAmbiguityBound95Deg": 0.0,
                "expectedCanonicalTrueHeadingDeg": normalize360(355.0 + 8.29),
            },
        ],
    }


def build_state_reducer() -> dict:
    happy_path = [
        "SESSION_STARTED",
        "LOCATION_ACQUIRED",
        "ORIENTATION_STREAM_READY",
        "CALIBRATION_CHECK_COMPLETED",
    ]
    return {
        "fixtureVersion": FIXTURE_VERSION,
        "specSections": ["§18.2", "§18.5"],
        "sequences": [
            {
                "id": "cold-start-to-degraded",
                "events": [
                    *[{"type": name} for name in happy_path],
                    {"type": "MAGNETIC_STATE_OBSERVED", "magneticState": "CLEAN"},
                    {"type": "POSE_VALID"},
                    {"type": "STABILITY_SATISFIED"},
                    {
                        "type": "BOUND_COMPOSED",
                        "reportedBound95Deg": 7.0,
                        "lockCeilingDeg": 5.0,
                        "lowConfidenceCeilingDeg": 10.0,
                    },
                ],
                "expectedFinalState": "DEGRADED",
                "expectedFinalEffects": [
                    "RECORD_STATE_TRANSITION",
                    "CLEAR_ACQUISITION_TIMEOUT",
                    "EMIT_DEGRADED_MEASUREMENT",
                ],
                "expectedLockHeld": False,
            },
            {
                "id": "certified-jig-locks",
                "events": [
                    *[{"type": name} for name in happy_path],
                    {"type": "MAGNETIC_STATE_OBSERVED", "magneticState": "CLEAN"},
                    {"type": "POSE_VALID"},
                    {"type": "STABILITY_SATISFIED"},
                    {
                        "type": "BOUND_COMPOSED",
                        "reportedBound95Deg": 1.7,
                        "lockCeilingDeg": 5.0,
                        "lowConfidenceCeilingDeg": 10.0,
                    },
                ],
                "expectedFinalState": "PRECISION_LOCKED",
                "expectedFinalEffects": [
                    "RECORD_STATE_TRANSITION",
                    "CLEAR_ACQUISITION_TIMEOUT",
                    "EMIT_LOCKED_MEASUREMENT",
                ],
                "expectedLockHeld": True,
            },
            {
                "id": "bound-above-low-confidence-is-invalid",
                "events": [
                    *[{"type": name} for name in happy_path],
                    {"type": "MAGNETIC_STATE_OBSERVED", "magneticState": "CLEAN"},
                    {"type": "POSE_VALID"},
                    {
                        "type": "BOUND_COMPOSED",
                        "reportedBound95Deg": 12.0,
                        "lockCeilingDeg": 5.0,
                        "lowConfidenceCeilingDeg": 10.0,
                    },
                ],
                "expectedFinalState": "INVALID",
                "expectedFinalEffects": [
                    "RECORD_STATE_TRANSITION",
                    "RESET_AGGREGATION_WINDOW",
                    "EMIT_NO_MEASUREMENT",
                ],
                "expectedLockHeld": False,
            },
            {
                "id": "timeout-emits-no-measurement",
                "note": (
                    "Failure mode 26: a timeout goes to TIMED_OUT and emits no measurement. "
                    "It must not freeze the last number as a lock."
                ),
                "events": [
                    *[{"type": name} for name in happy_path],
                    {"type": "MAGNETIC_STATE_OBSERVED", "magneticState": "CLEAN"},
                    {"type": "POSE_VALID"},
                    {"type": "ACQUISITION_TIMED_OUT"},
                ],
                "expectedFinalState": "TIMED_OUT",
                "expectedFinalEffects": [
                    "RECORD_STATE_TRANSITION",
                    "RESET_AGGREGATION_WINDOW",
                    "EMIT_NO_MEASUREMENT",
                ],
                "expectedLockHeld": False,
            },
            {
                "id": "disturbed-invalidates-a-live-lock",
                "events": [
                    *[{"type": name} for name in happy_path],
                    {"type": "MAGNETIC_STATE_OBSERVED", "magneticState": "CLEAN"},
                    {"type": "POSE_VALID"},
                    {"type": "STABILITY_SATISFIED"},
                    {
                        "type": "BOUND_COMPOSED",
                        "reportedBound95Deg": 1.7,
                        "lockCeilingDeg": 5.0,
                        "lowConfidenceCeilingDeg": 10.0,
                    },
                    {"type": "MAGNETIC_STATE_OBSERVED", "magneticState": "DISTURBED"},
                ],
                "expectedFinalState": "INVALID",
                "expectedFinalEffects": [
                    "RECORD_STATE_TRANSITION",
                    "RESET_AGGREGATION_WINDOW",
                    "EMIT_NO_MEASUREMENT",
                ],
                "expectedLockHeld": False,
            },
            {
                "id": "unknown-magnetic-state-cannot-lock",
                "events": [
                    *[{"type": name} for name in happy_path],
                    {"type": "MAGNETIC_STATE_OBSERVED", "magneticState": "UNKNOWN"},
                ],
                "expectedFinalState": "INVALID",
                "expectedFinalEffects": [
                    "RECORD_STATE_TRANSITION",
                    "RESET_AGGREGATION_WINDOW",
                    "EMIT_NO_MEASUREMENT",
                ],
                "expectedLockHeld": False,
            },
            {
                "id": "backgrounding-resets-the-window",
                "events": [
                    *[{"type": name} for name in happy_path],
                    {"type": "MAGNETIC_STATE_OBSERVED", "magneticState": "CLEAN"},
                    {"type": "POSE_VALID"},
                    {"type": "STABILITY_SATISFIED"},
                    {
                        "type": "BOUND_COMPOSED",
                        "reportedBound95Deg": 1.7,
                        "lockCeilingDeg": 5.0,
                        "lowConfidenceCeilingDeg": 10.0,
                    },
                    {"type": "APP_BACKGROUNDED"},
                ],
                "expectedFinalState": "INVALID",
                "expectedFinalEffects": [
                    "RECORD_STATE_TRANSITION",
                    "RESET_AGGREGATION_WINDOW",
                    "EMIT_NO_MEASUREMENT",
                ],
                "expectedLockHeld": False,
            },
            {
                "id": "screen-rotation-invalidates-the-window",
                "events": [
                    *[{"type": name} for name in happy_path],
                    {"type": "MAGNETIC_STATE_OBSERVED", "magneticState": "CLEAN"},
                    {"type": "POSE_VALID"},
                    {"type": "SCREEN_ORIENTATION_CHANGED"},
                ],
                "expectedFinalState": "INVALID",
                "expectedFinalEffects": [
                    "RECORD_STATE_TRANSITION",
                    "RESET_AGGREGATION_WINDOW",
                    "EMIT_NO_MEASUREMENT",
                ],
                "expectedLockHeld": False,
            },
            {
                "id": "provider-initialization-is-not-calibration",
                "note": (
                    "§18.4 / failure mode 37: the sensor may be perfectly calibrated; the "
                    "fusion has simply not observed enough rotation to bound its own error."
                ),
                "events": [
                    {"type": "SESSION_STARTED"},
                    {"type": "LOCATION_ACQUIRED"},
                    {"type": "ORIENTATION_STREAM_READY"},
                    {"type": "PROVIDER_INITIALIZATION_REQUIRED"},
                ],
                "expectedFinalState": "PROVIDER_INITIALIZING",
                "expectedFinalEffects": [
                    "RECORD_STATE_TRANSITION",
                    "RESET_AGGREGATION_WINDOW",
                ],
                "expectedLockHeld": False,
            },
        ],
    }


def build_certification_key() -> dict:
    complete = {
        "certificationSchemaVersion": "certification-v1",
        "hardwareRuntimeIdentity": "ANDROID:example-runtime-tuple",
        "sensorRuntimeIdentity": (
            "sha256:6e7dadbedc4e1dc16778e4e1a63cd118ce33d61a0e409cd063332d4e00efc8fc"
        ),
        "osBuildIdentity": "example-exact-build",
        "providerId": "GOOGLE_FOP",
        "providerRuntimeIdentity": "GMS:example-exact-version",
        "providerErrorSource": "GOOGLE_CONSERVATIVE",
        "locationProviderId": "GOOGLE_FLP",
        "locationProviderRuntimeIdentity": "GMS:example-exact-version",
        "measurementMode": "FLAT_TOP_EDGE",
        "placementMethod": "FREEHAND",
        "placementProfileHash": (
            "sha256:81a1337acfb20f8c40a31ef2a70233cbaf772314f3e2287eee0db14dabf23c64"
        ),
        "geomagneticModelId": "WMM2025",
        "geomagneticCoefficientHash": "NOT_VENDORED",
        "geomagneticErrorModelHash": "NOT_VENDORED",
        "deviationCorrectionProfileHash": "NONE",
        "engineDecisionLogicHash": (
            "sha256:64a844e67c0a485dd3ce0cbed2f1c27324b2baaa0e11395928ed3ffe047824c6"
        ),
        "precisionConfigHash": (
            "sha256:e85a0eb4073a38c43828a294db750c7ee3ca5b7a17165b34650c8c40a99fab6f"
        ),
    }
    return {
        "fixtureVersion": FIXTURE_VERSION,
        "specSections": ["§24", "§19.1"],
        "completeKey": complete,
        "shippedDatabaseRecordCount": 0,
        "expectedLookupOnShippedDatabase": {
            "boundCalibrationState": "CANDIDATE",
            "uncertaintyCoverageEvidenceState": "TARGET_ONLY",
            "supportedQualityGrade": "USABLE",
            "deviceFloorSource": "unknownDeviceFloor95Deg",
        },
        "keyComponentsThatMustDifferentiate": [
            "providerErrorSource",
            "locationProviderRuntimeIdentity",
            "placementProfileHash",
            "geomagneticErrorModelHash",
            "engineDecisionLogicHash",
            "precisionConfigHash",
            "measurementMode",
        ],
        "rejectedOpenEndedIdentities": [
            "GMS:21.3.0+",
            "android-15-*",
            "latest",
            "example-build..other-build",
            ">=1.0.0",
        ],
        "notRuntimeObservableSentinel": "NOT_RUNTIME_OBSERVABLE",
    }


def build_telemetry_codec() -> dict:
    return {
        "fixtureVersion": FIXTURE_VERSION,
        "specSections": ["§22", "§22.2"],
        "rejectedDocuments": [
            {
                "id": "nonfinite-nan",
                "line": '{"schemaVersion":"1.0.0","payload":{"trueHeadingDeg":NaN}}',
                "reason": "JSON has no NaN literal",
            },
            {
                "id": "nonfinite-infinity",
                "line": '{"schemaVersion":"1.0.0","payload":{"trueHeadingDeg":Infinity}}',
                "reason": "JSON has no Infinity literal",
            },
            {
                "id": "snake-case-property-key",
                "line": '{"schema_version":"1.0.0","payload":{}}',
                "reason": "property keys are lowerCamelCase",
            },
            {
                "id": "upper-camel-property-key",
                "line": '{"SchemaVersion":"1.0.0","payload":{}}',
                "reason": "property keys are lowerCamelCase",
            },
        ],
        "roundTripDoubles": [
            0.1,
            0.30000000000000004,
            189.0,
            1e-7,
            123456789.123456789,
            -0.0,
            359.9999998999999,
        ],
        "commaDecimalLocales": ["de_DE.UTF-8", "fr_FR.UTF-8", "pt_BR.UTF-8"],
        "unknownEventTypes": ["engineOutput", "ENGINE_OUTPUT", "engine output", "not_an_event"],
    }


#: §37.1: "commit schemas, config, canonical types, angle/quaternion vectors, WMM vectors,
#: replay fixtures, rule boundaries, and vendored NOAA hashes; tag that baseline fixtures-v1".
FROZEN_MANIFEST = "testdata/fixtures-v1.manifest.json"

FROZEN_ARTIFACTS: tuple[str, ...] = (
    "config/feng-shui-rules-v1.json",
    "config/precision-profile-v1.json",
    "schemas/feng-shui-rules-v1.schema.json",
    "schemas/precision-profile-v1.schema.json",
    "schemas/session-manifest-v1.schema.json",
    "schemas/telemetry-event-v1.schema.json",
    "testdata/grade-reachability-claims-v1.json",
    "testdata/session-manifest-v1.example.json",
    "testdata/telemetry-event-engine-output-v1.example.json",
    "testdata/angles/circular-math-v1.json",
    "testdata/angles/estimators-v1.json",
    "testdata/angles/circular-aggregate-v1.json",
    "testdata/quaternions/attitude-golden-v1.json",
    "testdata/fengshui/classification-v1.json",
    "testdata/fengshui/reference-transform-v1.json",
    "testdata/uncertainty/composition-v1.json",
    "testdata/magnetic/classification-v1.json",
    "testdata/reference/resolution-v1.json",
    "testdata/state/reducer-v1.json",
    "testdata/certification/key-v1.json",
    "testdata/telemetry/codec-v1.json",
    "third_party/noaa-wmm/sha256.txt",
)


def build_manifest() -> dict:
    """The `fixtures-v1` hash manifest: what is frozen, and at which bytes.

    `third_party/noaa-wmm/sha256.txt` is included deliberately even though it currently holds
    no entries: freezing the *declared* NOT_VENDORED state means a later vendoring is a visible
    contract change rather than a silent one (D-2).
    """
    import hashlib

    return {
        "fixtureVersion": FIXTURE_VERSION,
        "specSections": ["§37.1"],
        "note": (
            "Frozen before platform work diverges. Neither platform agent edits these "
            "unilaterally; a contract change requires one reviewed change set, regenerated "
            "fixtures, both test suites, and a new fixture version."
        ),
        "declaredAngleToleranceDeg": DECLARED_ANGLE_TOLERANCE_DEG,
        "artifacts": {
            relative: "sha256:"
            + hashlib.sha256((REPO_ROOT / relative).read_bytes()).hexdigest()
            for relative in FROZEN_ARTIFACTS
        },
    }


def write(path: Path, document: dict, check: bool) -> bool:
    text = json.dumps(document, indent=2, ensure_ascii=False, allow_nan=False) + "\n"
    if check:
        if not path.is_file() or path.read_text(encoding="utf-8") != text:
            print(f"STALE: {path.relative_to(REPO_ROOT)}", file=sys.stderr)
            return False
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    print(f"wrote {path.relative_to(REPO_ROOT)}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of writing when a committed fixture is stale",
    )
    arguments = parser.parse_args()

    rule_set = json.loads(
        (REPO_ROOT / "config" / "feng-shui-rules-v1.json").read_text(encoding="utf-8")
    )
    profile = json.loads(
        (REPO_ROOT / "config" / "precision-profile-v1.json").read_text(encoding="utf-8")
    )

    outputs = {
        "testdata/angles/circular-math-v1.json": build_circular_math(),
        "testdata/angles/estimators-v1.json": build_estimators(),
        "testdata/angles/circular-aggregate-v1.json": build_circular_aggregate(profile),
        "testdata/quaternions/attitude-golden-v1.json": build_attitude_golden(),
        "testdata/fengshui/classification-v1.json": build_fengshui_classification(rule_set),
        "testdata/fengshui/reference-transform-v1.json": build_fengshui_reference_transform(),
        "testdata/uncertainty/composition-v1.json": build_uncertainty_composition(profile),
        "testdata/magnetic/classification-v1.json": build_magnetic_classification(profile),
        "testdata/reference/resolution-v1.json": build_reference_resolution(profile),
        "testdata/state/reducer-v1.json": build_state_reducer(),
        "testdata/certification/key-v1.json": build_certification_key(),
        "testdata/telemetry/codec-v1.json": build_telemetry_codec(),
    }

    ok = True
    for relative, document in outputs.items():
        ok &= write(REPO_ROOT / relative, document, arguments.check)

    # §37.1: freeze the whole shared contract, not only the generated part. The manifest is
    # written last because it hashes the files above.
    ok &= write(REPO_ROOT / FROZEN_MANIFEST, build_manifest(), arguments.check)
    if arguments.check and not ok:
        print(
            "\nRun scripts/generate-shared-fixtures.py to regenerate. A contract change "
            "requires one reviewed change set, regenerated fixtures, both test suites, and a "
            "new fixture version (§37.1).",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
